hw10
vsPEach/hw-otus pull request #17
Opened 2023-03-19 12:48 UTC by vsPEach

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-03-20 20:58 UTC, vsPEach reviewed
Benchstat result

<img width="532" alt="image" src="https://user-images.githubusercontent.com/76450185/226464358-0436fb62-7ec2-43d8-8fc4-11de47e02288.png">

2023-05-06 09:57 UTC, dshemin approved these changes

2023-05-06 09:57 UTC, dshemin commented on hw10_program_optimization/go.mod
> +module github.com/vsPEach/hw10_program_optimization
Критично:

Тут должно быть github.com/vsPEach/hw-otus/hw10_program_optimization

2023-05-06 09:57 UTC, dshemin commented on hw10_program_optimization/stats.go
>  type users [100_000]User
Важно:

У нас осталось выделение непрерывного участка памяти для 100 000 объектов типа User.  Без этого можно обойтись.

2023-05-06 09:57 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		if errors.Is(err, io.EOF) {
Важно:

Обработать ошибку нужно до того как мы используем результат функции.

2023-05-06 09:57 UTC, dshemin commented on hw10_program_optimization/stats.go
>  	for _, user := range u {
Важно:

На данный момент мы:
1. Сначала пробегаемся по файлу и формируем список структур
2. Пробегаем по списку чтобы что-то посчитать

Как итог: Мы дважды итерируемся +  у нас линейное потребление памяти. Можно сделать за одну итерацию и константное потребление памяти.

2023-05-12 15:19 UTC, dshemin requested changes

2023-05-12 15:19 UTC, dshemin commented on hw10_program_optimization/stats_optimization_test.go
> +	r, err := zip.OpenReader("testdata/users.dat.zip")
Важно:

Пайплайн в гитхабе не гарантирует что успеет разобрать 17 мегабайт данных в установленный период.

2023-05-13 03:17 UTC, dshemin approved these changes

2023-05-13 05:40 UTC, merged