Hw12
vsPEach/hw-otus pull request #19
Opened 2023-04-21 07:46 UTC by vsPEach

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2023-05-06 02:31 UTC, dshemin requested changes

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/build/Dockerfile
> +ENV CONFIG_FILE /etc/calendar/config.yml
Важно:

У нас есть переменная окружения, но она не используется.

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/config/config.go
> +func (db DatabaseConf) GetConnectionString() string {
Важно:

Строка соединения специфична для БД. Не стоит детали реализации держать тут.

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/go.mod
> +module github.com/vsPEach/hw12_13_14_15_calendar
Критично:

Надо было заменить `fixme_my_friend` на `vsPEach/hw-otus`

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +type Logger interface {
Важно:

Уже не впервый раз вижу определение этого интерфейса. Надо утажить его в пакет с логером. Или, если хотите чтобы интерфейс лежал там, где он используется, то вырежете все не используемые методы.

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +type Logger interface {
Важно:

Данный тип не зависит от лоегра, интерфейс тут не нужен.

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	s.mp[event.ID] = event
Важно:

Изменение мапы вне мютекса, тут будет race condition!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	s.mp[id] = event
Важно:

Изменение мапы вне мютекса, тут будет race condition!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	for _, event := range s.mp {
Важно:

Итерация по мапе вне мютекса, тут будет race condition!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	for _, event := range s.mp {
Важно:

Итерация по мапе вне мютекса, тут будет race condition!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	for _, event := range s.mp {
Важно:

Итерация по мапе вне мютекса, тут будет race condition!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +		mu: sync.RWMutex{},
Совет:

Не надо явной инициализации для мютекса.

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	err := s.conn.Select(&events,
Важно:

Делаем, по сути, запрос по сети к внешнему сервису. Без контекста, следовательно, не можем управлять данным запросом. Это крайне важно! Добавьте контекст во все методы стораджа!

2023-05-06 02:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
>  	return nil
Важно:

У соединения с БД есть метод для закрытия. Его тут надо вызвать.

2023-05-07 09:23 UTC, dshemin approved these changes

2023-05-07 09:23 UTC, dshemin commented on hw12_13_14_15_calendar/build/Dockerfile
> +CMD ${BIN_FILE} --config /etc/calendar/config.yml
Важно:

Тут тоже надо использовать переменную окружения CONFIG_FILE

2023-05-07 09:39 UTC, vsPEach commented on hw12_13_14_15_calendar/build/Dockerfile
> +CMD ${BIN_FILE} --config /etc/calendar/config.yml
Исправлю в PR на 13 ветке

2023-05-07 21:17 UTC, merged