Hw03 frequency analysis
vsPEach/hw-otus pull request #3
Opened 2022-12-17 23:12 UTC by vsPEach

2022-12-23 00:05 UTC, Nikscorp requested changes
Никита, добрый день.

Спасибо а проделанную работу, код лаконичен.
Оставил несколько критичных замечаний к PR, прошу исправить.

> **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)

2022-12-23 00:05 UTC, Nikscorp commented on hw03_frequency_analysis/top_test.go
> +			tests := []struct {
CRITICAL: написанные вами тесты не запустятся, так как `taskWithAsteriskIsCompleted = false`

2022-12-23 04:25 UTC, vsPEach commented on hw03_frequency_analysis/top.go
> +	return keys[:10]
Да. Я ошибся, не заметил что что условие по-другому выглядит

2022-12-26 20:56 UTC, Nikscorp approved these changes
Никита, добрый день!

Замечания исправлены, теперь все хорошо.
Работа принята, ставлю максимальный балл.
Оставил еще несколько замечаний не влияющих на оценку.

2022-12-26 20:56 UTC, Nikscorp commented on hw03_frequency_analysis/top.go
> +	top := make(map[string]int)
NB: top не очень удачный нейминг, это скоре `wordFreq` или что-то вроде того

2022-12-26 20:56 UTC, Nikscorp commented on hw03_frequency_analysis/top_test.go
> +			for _, test := range tests {
NB: если вы пишете табличные тесты, запускайте из через `t.Run`, чтобы было видно, что это разные тесты: https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

2022-12-26 20:56 UTC, Nikscorp commented on hw03_frequency_analysis/top.go
> +	sort.Slice(keys, func(i, j int) bool {
NB: можно добиться лучшей time comlexity если вместо сортировки использовать `container/heap`

2022-12-26 22:03 UTC, merged