hw05 was complete
vsPEach/hw-otus pull request #6
Opened 2023-02-07 23:09 UTC by vsPEach

Reopen last pull request

2023-02-12 23:42 UTC, Nikscorp requested changes
Написал вещи на которые стоит обратить внимание, чтобы решение заработало

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, len(tasks))
Вместо такого большого буфера лучше просто сначала запустите воркеров, а затем пишите в канал с тасками, тогда канал может быть даже небуферизованным

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +	for _, task := range tasks {
Как только сложили таски в канал — закройте его

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +				case t, ok := <-tasksCh:
Лучше просто читайте канал с тасками в range

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +					if errCount == m {
рейс, читать значение переменной нужно тоже с мьютексом

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +						interruptCh <- struct{}{}
Зачем этот interruptCh? Просто проверьте число ошибок в основной горутине

2023-02-12 23:42 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +	wg.Wait()
Сначала Wait, а потом уже проверьте число ошибок и верните лучший результат

2023-02-20 19:48 UTC, nurlybekovnt commented on hw05_parallel_execution/run.go
> +		if errorCount < m {
Доступ к переменной `errorCount` осуществляется из других горутин, которые были созданы циклом выше. Там Вы защищаете переменную `errorCount` мьютексом `mx`, а здесь не защищаете. Дело в том, что первая горутина, которая вызовет функцию `mx.Lock()` получит доступ к переменной, а остальные горутины вызвавшие `mx.Lock()` заблокируются на исполнении `mx.Lock()` и будут ждать пока первая горутина не вызовет `mx.Unlock()`, и освободит мьютекс. Получается доступ к переменной `errorCount` в единицу времени имеет только одна горутина, и не возникает состояние гонки. Остались вопросы?

2023-02-20 21:58 UTC, vsPEach commented on hw05_parallel_execution/run.go
> +		if errorCount < m {
Это понятно. Я так понимаю, нужна гарантия, что main горутина будет первой. Просто как бы я не оборачивал в этом цикле errCount в мьютекс возникает deadlock, поэтому есть определенное недопонимание как процесс просиходит лока происходит в этом месте.

2023-02-21 10:55 UTC, nurlybekovnt commented on hw05_parallel_execution/run.go
> +		if errorCount < m {
Нужна гарантия, что к переменной `errCount` не будет параллельных доступов. Никита, попробуйте запустить такой тест у себя с флагом `-race` так: `go test -race`:

```go

func TestRace(t *testing.T) {
	var (
		errCount int
		mu       sync.Mutex
		wg       sync.WaitGroup
	)

	// 100 горутин изменяют значение errCount в мьютексе
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()

			for j := 0; j < 100000; j++ {
				mu.Lock()
				errCount++
				mu.Unlock()
			}
		}()
	}

	for i := 0; i < 100000000; i++ {
		// одна горутина читает значение errCount
		if errCount == 100000000 {
			log.Println("errCount == 100000000")
		}
	}

	wg.Wait()
}

```

2023-02-27 16:57 UTC, nurlybekovnt commented on hw05_parallel_execution/run.go
> +					if errorCount == m {
Что будет если эту проверку убрать?

2023-03-05 12:20 UTC, vsPEach commented on hw05_parallel_execution/run.go
> +					if errorCount == m {
Горутины не будут принудительно останавливаться

2023-03-06 08:28 UTC, nurlybekovnt commented on hw05_parallel_execution/run.go
> +					if errorCount == m {
Добрый день, Никита! Попробуйте убрать ту проверку и запустить тесты повторно. Решение можно принимать, спасибо за выполненное домашнее задание. Отличная работа, 10 из 10!

2023-03-07 08:26 UTC, merged